### ISSUE TITLE
Add test project when creating a new module (optional)

### ISSUE THREAD

**Issue by patelcp** [PentiaLabs/generator-helix#101]
### User story
As a developer, I want the generator to create the test project when adding a new module so that I don't have to manually go back and add one in visual studio.

### Expected behavior
1. provide option to create a test project when adding a new module
2. create a blank test project

### Actual behavior
No test projects are created currently

**Comment by Saturate** [comment]
Seems like a really great idea, if anyone if up for it feel free to make a pull-request!

**Comment by patelcp** [comment]
@Saturate I'll take this on and will find some time next week to work on it.

**Comment by TakeitEasyAlan** [comment]
Hi @patelcp 

You can achieve this by extending the "add generator": https://github.com/PentiaLabs/generator-helix#extending-the-add-generator

The strategy for test projects varies from Sitecore partner to Sitecore partner: some put all tests into a single project, some split them into one project per "src-project", some add one project per layer, some do it based on user journeys (i.e. e2e-tests) - it's so diverse that I think it's out of scope to provide a built in template.
