### ISSUE TITLE
Serialization.config is generated with wrong name and in wrong folder

### ISSUE THREAD

**Issue by eriktbe** [PentiaLabs/generator-helix#103]
### User story
As a developer, I want the generated serialization.config file to be prefixed with the layer and module name and placed in a generic layer folder so that the structure is in line with the Helix principles and Habitat reference implementation.

### Expected behavior
When generating a new project, the serialization.config is generated with a file name of [Layer].[Module].serialization.config and placed in a folder called [Layer].

### Actual behavior

When generating a new project, the serialization.config is generated with a file name of 'serialization.config' and placed in a folder called [VendorPrefix].[Layer].[Module].

### Steps to reproduce the behavior

Run yo helix:add

**Comment by Saturate** [comment]
Hey @eriktbe thanks for reporting this in! We'll take a look at it very soon, won't we @TakeitEasyAlan? ;)

**Comment by TakeitEasyAlan** [comment]
Hi,

@eriktbe can confirm this is a bug, in that if the vendor is empty it should not create a folder called .Layer.Module (I will remove the . if the vendor is empty)

But if a vendor is specified should the sub folder for serialization be prefixed or not, the documentation for helix does not specify what to do therefore to ensure there are no conflicts it should be prefixed in case you have the same module from 2 vendors in the same layer.
