### ISSUE TITLE
Should one be able choose to have Pentia .dotfiles generated as well?

### ISSUE THREAD

**Issue by vajkri** [PentiaLabs/generator-helix#108]
### User story
As a frontender I don't want to have to remember adding .editorconfig, .eslint etc., this would be amazing if it happened automatically.

**Comment by TakeitEasyAlan** [comment]
Out of scope, as different Sitecore partners surely have different `.editorconfig` settings.
This can be achieved using the "extending the add generator" feature: https://github.com/PentiaLabs/generator-helix#extending-the-add-generator
