### ISSUE TITLE
git integration

### ISSUE THREAD

**Issue by Morksen** [PentiaLabs/generator-helix#110]
### User story
As a developer, I want the generator to include git repository creation.

### Expected behavior
* option to create a local git repository for solution
* automatically add .gitignore file (https://github.com/github/gitignore/blob/master/VisualStudio.gitignore)
* automatically add .gitattributes file
* option to add a git remote
* option to commit and push after solution generation

**Comment by TakeitEasyAlan** [comment]
The creation of `.gitignore` and `.gitattributes` can be achieved already, see [extending the add generator](https://github.com/PentiaLabs/generator-helix#extending-the-add-generator).

You could add a `bash`, `bat`, `cmd`, `ps1` etc. script which performs the Git actions, if the use case is prevalent in your everyday work.
