### ISSUE TITLE
Get-MsBuildPath.ps1 failes to return correct path

### ISSUE THREAD

**Issue by galtrold** [PentiaLabs/generator-helix#118]
### User story
I want to add a project to my solution.

### Expected behavior
A project is added to the desired layer

### Actual behavior
The action failes because it can't find MSBuild (Get-MsBuildPath.ps1).
It seem that it searches for a specific version i.e 14.0 
Suggestion: Use the same script/bat file that is used in WebSolutionBuildScripts https://github.com/PentiaLabs/WebSolutionBuildScripts/blob/master/Pentia.Get-MSBuild/Pentia.Get-MSBuild.psm1

### Steps to reproduce the behavior
Add a project to a helix solution on a new machine which only have the latest version MSBuild (v 15.0)

**Comment by TakeitEasyAlan** [comment]
Discussion moved to #109
