### ISSUE TITLE
Old VS new Serialization.config

### ISSUE THREAD

**Issue by peichhorndev** [PentiaLabs/generator-helix#119]
### User story
Sitecore crashes due to unset variables of Serialization.config
$(featureFolder)\HelloWorld\\$(configurationFolder)

Where do i have to set these Parameters?
Are there any default values?

### Expected behavior
Sitecore running like before

### Actual behavior
Actually using a Serialization.config like
[Habitat Serialization Config](https://github.com/Sitecore/Habitat/blob/feature/v9/src/Feature/Media/code/App_Config/Include/Feature/Feature.Media.Serialization.config)

**Comment by squadwuschel** [comment]
yes we are using the default settings for sitecore like in the habitat project v9 branch and with the latest update from the yeoman helix generator its not "working" anymore because you changed the generated config files. 

Is it possible to create my own dynamic config files with your supported variables or can you add a addional choise where I can choose If I want the original config files or the new ones?

**Comment by TakeitEasyAlan** [comment]
Sorry for the slow response (been out at a customer/summer etc.) hope to resolve/fix this next Friday, but you can always update the template files to match your requirements :-)

**Comment by TakeitEasyAlan** [comment]
You have to define them like any other Sitecore variable (`dataFolder` and `tempFolder` for instance), as Unicorn needs to know the path where the serialization files are stored.

E.g.:

```xml
<?xml version="1.0"?>
<configuration xmlns:patch="http://www.sitecore.net/xmlconfig/"
               xmlns:environment="http://www.sitecore.net/xmlconfig/environment">

  <sitecore environment:require="Development">
    <sc.variable name="featureFolder" value="D:\home\site\wwwroot\deploypackage\Data\s\fe" />
    <sc.variable name="foundationFolder" value="D:\home\site\wwwroot\deploypackage\Data\s\fo" />
    <sc.variable name="projectFolder" value="D:\home\site\wwwroot\deploypackage\Data\s\pr" />
    <sc.variable name="configurationFolder" value=""/>
  </sitecore>
</configuration>
```
