### ISSUE TITLE
Serialization.config is not added when Yes to Unicorn is selected

### ISSUE THREAD

**Issue by jsurland** [PentiaLabs/generator-helix#122]
### User story
As a Developer, I want a Serialization.config file so that unicorn will work and the project can build when just added a new helix project. (Please replace the <> areas and remove this parentheses)

### Expected behavior
serialization.config file added to the new project.

### Actual behavior
The file is missing, though the new project reference it.
Result is that the solution won't build.

### Steps to reproduce the behavior
yo helix:add Dummy RK

**Comment by TakeitEasyAlan** [comment]
Can not reproduce it
