### ISSUE TITLE
NPM Audit vulnerabilities

### ISSUE THREAD

**Issue by TomDudfield** [PentiaLabs/generator-helix#127]
We are currently seeing 3 vulnerabilities when running an NPM audit. Is it possible to get these addressed? 

  Critical        Command Injection
  Package         growl
  Patched in      >=1.10.2
  Dependency of   generator-helix
  Path            generator-helix > mocha > growl
  More info       https://nodesecurity.io/advisories/146

  Low             Regular Expression Denial of Service
  Package         debug
  Patched in      >= 2.6.9 < 3.0.0 || >= 3.1.0
  Dependency of   generator-helix
  Path            generator-helix > mocha > debug
  More info       https://nodesecurity.io/advisories/534

  Low             Prototype Pollution
  Package         deep-extend
  Patched in      >=0.5.1
  Dependency of   generator-helix
  Path            generator-helix > yeoman-generator > mem-fs-editor >
                  deep-extend
  More info       https://nodesecurity.io/advisories/612

**Comment by TomDudfield** [comment]
@TakeitEasyAlan and @uli-weltersbach thanks for getting this resolved. How do we get a new build onto npm?

**Comment by TakeitEasyAlan** [comment]
I planned to do this, Monday but I have been sick this week, and it is bank holiday in Denmark Friday, therefore I hope to test and release Monday next week (maybe Tuesday)

**Comment by TomDudfield** [comment]
> I planned to do this, Monday but I have been sick this week, and it is bank holiday in Denmark Friday, therefore I hope to test and release Monday next week (maybe Tuesday)

That's perfect, thanks

**Comment by TomDudfield** [comment]
Hi @TakeitEasyAlan 

Were you able to make any progress testing and releasing these changes?

**Comment by TakeitEasyAlan** [comment]
Have now released the new version with updated dependencies
