### ISSUE TITLE
.csproj file template contains hardcoded reference to VS v10.0 WebPublish build targets

### ISSUE THREAD

**Issue by uli-weltersbach** [PentiaLabs/generator-helix#128]
See https://github.com/PentiaLabs/generator-helix/blob/be799177917e8f42d0149d19c8b12151a7fa3ffb/generators/add/Templates/_project.csproj#L72

This causes errors on computers which don't have VS 10.0 WebPublish targets installed (i.e. all computers which don't have VS 2010 installed).

**Comment by TakeitEasyAlan** [comment]
Hi,

Well using the the feature where you can override any of the default files, by modifying the template, either globally or per project see https://www.npmjs.com/package/generator-helix, but I aggree that we should update the include to VS 2017

**Comment by uli-weltersbach** [comment]
I didn't realize the lines were marked as `Condition="false"`, so they should just be deleted.

- https://github.com/PentiaLabs/generator-helix/blob/be799177917e8f42d0149d19c8b12151a7fa3ffb/generators/app/Templates/Project/Environment/Project.Environment.csproj#L78

- https://github.com/PentiaLabs/generator-helix/blob/c2794744446f73332a7169e341c614aed2862afe/generators/add/Templates/_project.csproj#L72

- https://github.com/PentiaLabs/generator-helix/blob/c2794744446f73332a7169e341c614aed2862afe/generators/add/Templates/_project.unicorn.csproj#L75
