### ISSUE TITLE
Add folders: /Controllers, /Models and /Views

### ISSUE THREAD

**Issue by snyhde** [PentiaLabs/generator-helix#23]

**Comment by TakeitEasyAlan** [comment]
@snyhde see https://sop.pentia.dk/Home/Backend/Modular%20Architecture/DDD%20Project%20Structure/
there should not be a Models folder (as it is not correct DDD) 
But I will add the models & Views + the web.config etc.

**Comment by soen** [comment]
@TakeitEasyAlan I think it would be a good idea to let this be something that is optional when creating the project. If you create a foundation project, chances are that you don't even need to things included in the first place.

**Comment by Hafeok** [comment]
Closing this - this can now be done using the new template feature. See issue #2 and the documentation has been updated :)
