### ISSUE TITLE
Add T4 templates

### ISSUE THREAD

**Issue by TakeitEasyAlan** [PentiaLabs/generator-helix#29]
### User story
As a Developer I would like the option to add the T4 templates.

**Comment by TakeitEasyAlan** [comment]
![image](https://cloud.githubusercontent.com/assets/9886931/22732154/74d41b8c-eded-11e6-82fe-134c71e42f47.png)

**Comment by soen** [comment]
@TakeitEasyAlan Was this feature implemented, I don't see any associated PR? It seems like both #42 and #37 are somewhat related to, and relying on, this feature.
