### ISSUE TITLE
Error adding feature project due to spaces in the path of the module

### ISSUE THREAD

**Issue by snyhde** [PentiaLabs/generator-helix#35]
D:\Projects\Bane.Website [formsprojecthelixway]> npm install generator-helix -g
C:\Program Files\nodejs
`-- generator-helix@1.0.5

D:\Projects\Bane.Website [formsprojecthelixway]> yo helix:add Feature.Forms

     _-----_
    |       |    ╭──────────────────────────╮
    |--(o)--|    │    Lets generate that    │
   `---------´   │         project!         │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? Name of your project Feature.Forms
? Would you like to include Unicorn (serialization)? Yes
? Source code folder name src
? What layer do you want to add the project too? Feature layer?
? Choose target .net framework version? .net 4.6.1
Powershell - running: C:\Program Files\nodejs\node_modules\generator-helix\powershell\add-project.ps1 -SolutionFile 'D:\Projects\Bane.Website\Bane.Website.sln' -Name Feature.Feature.Forms -Type Feature -ProjectPath 'src\Feature\Feature.Forms\code' -SolutionFolderName Fea
ture.Forms
   create src\Feature\Feature.Forms\code\Feature.Feature.Forms.csproj
   create src\Feature\Feature.Forms\code\Properties\AssemblyInfo.cs
   create src\Feature\Feature.Forms\code\App_Config\Include\Feature.Feature.Forms\serialization.config
   create src\Feature\Feature.Forms\code\Properties\PublishProfiles\local.pubxml
Error: C:\Program : The term 'C:\Program' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Error: At line:1 char:1
+ C:\Program Files\nodejs\node_modules\generator-helix\powershell\add-p ...
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Powershell - done running C:\Program Files\nodejs\node_modules\generator-helix\powershell\add-project.ps1-SolutionFile 'D:\Projects\Bane.Website\Bane.Website.sln' -Name Feature.Feature.Forms -Type Feature -ProjectPath 'src\Feature\Feature.Forms\code' -SolutionFolderName
Feature.Forms
D:\Projects\Bane.Website [formsprojecthelixway +1 ~0 -0 !]>

![image](https://cloud.githubusercontent.com/assets/16254312/22694456/9caa10ea-ed47-11e6-9d67-e82f9741adc9.png)

**Comment by TakeitEasyAlan** [comment]
I can reproduce when I move by repo, to a path with spaces and then link (npm link) it seems that the following line, has issues with the space

var child = spawn("powershell.exe", [pathToScriptFile, parameters]);
