### ISSUE TITLE
Add Sitecore.Kernel.NoReferences and RainbowCodeGeneration to project references

### ISSUE THREAD

**Issue by snyhde** [PentiaLabs/generator-helix#37]

**Comment by istern** [comment]
To ensure best solution for wishes and issues please follow the guide lines found in the issue template and listed below. Also references should be made in package file with a reference to nuget file so you can restore the missing packages inside visual studio.
User story

As a , I want so that . (Please replace the <> areas and remove this parentheses)

Expected behavior

Actual behavior

Steps to reproduce the behavior

**Comment by TakeitEasyAlan** [comment]
@snyhde  I don't believe we should dictate what references are included, as it is possible that they don't need to reference sitecore and or they might not use T4 i.e. RainbowCodeGeneration

**Comment by soen** [comment]
I fully agree with @TakeitEasyAlan on this part. As long as the solution structure comes with a pre-configured package source to Sitecore's NuGet feed, then we should be set.

**Comment by snyhde** [comment]
I would like a practical generator that do all the work that I do manually 99% of the time (and that includes adding the sitecore dll and rainbow dll and t4 templates). How do I extend the functionality?

**Comment by soen** [comment]
It sounds like this is related to #2, whereas the extensibility model should allow clients of the API to hook into the project creation process.

In this concrete example, I'm thinking that one of the default extension hooks would be 'adding NuGet references to a project'. The extension hook could be provided with a specification (json file), that tells the generator which NuGet references to add, including the specific version of the NuGet package.

What do you think @TakeItEasyAlan?

**Comment by soen** [comment]
Also, another extension point could be the adding of T4 template files to the project, where to specify the T4 template you want to add and where it should be added into the project - which is also something you ask for, @snyhde. Moreover, this sounds to be related to #42?

**Comment by TakeitEasyAlan** [comment]
@snyhde @soen I believe that @Hafeok has now added the ability to add your own files to the generator... i.e. #2 I might want to take it a step further but that will be at the end of this week

**Comment by Hafeok** [comment]
Closing this - this can now be done using the new template feature. See issue #2 and the documentation has been updated :)
