### ISSUE TITLE
Add Sitecore configuration file /App_Config/Include/<projectname>/<projectname>.config upon project creation

### ISSUE THREAD

**Issue by snyhde** [PentiaLabs/generator-helix#39]

**Comment by istern** [comment]
**You have to add better descriptions to issues !!!**

**Comment by teltploek** [comment]
Thank you for your interest and activity in the project, @snyhde 😄 

As stated by @istern, the initial maintainers of this project has set a minimum requirement for feature requests (read below). Thank you very much for your contributions, but please respect these guidelines - by doing so you will probably even make it possible for more people to understand your intend and to resolve your issues.

---

## Help us! Keep the quality of issues high

We strive to make it possible for everyone and anybody to contribute to this project. Please help us by making issues easier to resolve by providing sufficient information. Understanding the reasons behind issues can take a lot of time if information is left out. Time that we could rather spend on fixing bugs and adding features. Please adhere to our issues template when creating issues. Creating a new issues will automatically prompt a template that will let you know what the minimum requirements are.

Thank you, and happy contributing!

**Comment by snyhde** [comment]
OK. As stated in the issue title I would like a config file as part of the setup of a new helix project. It could be just an empty template for future additions or include some basic commented out examples i.e. the content could be something around these lines (to get the developer efficiently up and running in no time): 
```
<configuration xmlns:patch="http://www.sitecore.net/xmlconfig/">
<!-- sample configuration for adding a pipeline step -->
<!--
<sitecore>
    <pipelines>
      <httpRequestBegin>
        <processor type="Some.NameSpace.For.Doing.Stuff, Some.NameSpace" patch:after="processor[@type='Some.NameSpace.For.Doing.Stuff.Processor, Some.NameSpace']"/>
      </httpRequestBegin>
    <pipelines>
<sitecore>
--> 

<!-- adding settings -->
<!--
<sitecore>
    <settings>
        <setting name="SomeSetting.Name" value="SomeSettingValue"/>
    </settings>
</sitecore>
-->
</configuration>
```

And I would like it to be added in the "/App_Config/Include/`<projectname folder>`/" folder (cause that's where the Unicorn serialization/configuration is already placed and because it makes sense) and I would like that the configuration file is named "`<project name>`.config" (so the configuration file would have a globally unique name).

**Comment by Hafeok** [comment]
This will not be added to the core of the helix-generator. 

When the #2 is implemented then you are more than welcome to add it as a something specific to your own template. But we wont be adding it is a core feature, since it is standard Sitecore functionality.
