### ISSUE TITLE
Add T4 templates with rainbowcodegeneration and update the template to include field id's with curly brackets ("{" and "}")

### ISSUE THREAD

**Issue by snyhde** [PentiaLabs/generator-helix#42]
Let field types have "{" and "}" in when creating the new ID.
i.e.
WRONG: public static readonly ID FieldId = new ID("d582b575-5fa5-463c-bcc7-e840fa83a995");
CORRECT: public static readonly ID FieldId = new ID("{d582b575-5fa5-463c-bcc7-e840fa83a995}");

Both way will compile and work. But in the real world and working with Sitecore - devs usually copy the ID of a item (including the "{" and "}" i.e. "{d582b575-5fa5-463c-bcc7-e840fa83a995}") and search the VS solution for the specific item ID. So if the T4 templates leave out the curly brackets the VS search hit is missed.

Note: per default the T4 template does create the ID of the template items with curly brackets - so it seems intentionel or simply an oversight to leave out the curly brackets when creating the data template ID's.

**Comment by Hafeok** [comment]
Closing this - this can now be done using the new template feature. See issue #2 and the documentation has been updated :)
