### ISSUE TITLE
Error with 'Path must be a string' on add project

### ISSUE THREAD

**Issue by Fillej** [PentiaLabs/generator-helix#48]
As a developer, I'm trying to add a project in an Empty Helix Solution.

Instead of generating the new project i'm getting an error message on the 'path must be a string':

> 
> events.js:161
>       throw er; // Unhandled 'error' event
>       ^
> 
> TypeError: Path must be a string. Received undefined
>     at assertPath (path.js:7:11)
>     at Object.join (path.js:468:7)
>     at Object.Base.destinationPath (PATHTOGLOBAL\npm\node_modules\generator-helix\node_modules\yeoman-generator\lib\index.js:637:28)
>     at Object.writing (PATHTOGLOBAL\npm\node_modules\generator-helix\generators\add\index.js:148:62)
>     at Object.<anonymous> (PATHTOGLOBAL\npm\node_modules\generator-helix\node_modules\yeoman-generator\lib\index.js:408:23)
>     at PATHTOGLOBAL\npm\node_modules\generator-helix\node_modules\run-async\index.js:25:25
>     at PATHTOGLOBAL\npm\node_modules\generator-helix\node_modules\run-async\index.js:24:19
>     at PATHTOGLOBAL\npm\node_modules\generator-helix\node_modules\yeoman-generator\lib\index.js:409:9
>     at runCallback (timers.js:651:20)
>     at tryOnImmediate (timers.js:624:5)

## Steps to reproduce the behavior

To see this error

1. run yo helix. Choose the option "Empty Helix Solution"

2. run yo helix:add

**Comment by Hafeok** [comment]
Hey, what version is was this discored on?

Try and update to newest version :)

**Comment by Hafeok** [comment]
this has been fixed and pushed. Try the newest generator :)
