### ISSUE TITLE
Add licence file and license block to readme 

### ISSUE THREAD

**Issue by Saturate** [PentiaLabs/generator-helix#55]
We should have a more clear license, without a license file and statement in the readme it's a bit hard.

Would recommend MIT or GPL.

**Comment by jsurland** [comment]
Sure about GPL? GPL can be problematic in some scenarios. MIT is my suggestion.

**Comment by Saturate** [comment]
I guess MIT is the best one, as it's simple and allows . However some might say that [GPL](https://choosealicense.com/licenses/gpl-3.0/) would fit this project and still allow for it's use.

I would just go MIT, and call it a nice day. However I guess we need to think a bit about it, take a look at https://choosealicense.com/. 

I don't know how is responsible for this, but we need to add one soon :-)

**Comment by ronnidc** [comment]
What's the big difference between the existing [ISC ](https://opensource.org/licenses/ISC) license referenced in package.json and the [MIT](https://choosealicense.com/licenses/mit/)? 

As far as I can tell the only difference is that ISC is written in shorter and fewer sentences but they both share the same meaning.

I do agree that a license file should be included in the repo.

**Comment by jsurland** [comment]
If you at ANY time make a product, that uses any of a GPL license you have to give anyone the whole source of your product, if they ask. It's a nasty license for product creators.

**Comment by Saturate** [comment]
MIT as well @jsurland  is my vote, but again I have no idea who can decide this? Maybe it's you :-)
