### ISSUE TITLE
Documentation for extending the generator

### ISSUE THREAD

**Issue by istern** [PentiaLabs/generator-helix#56]
As a Developer, I want to extend the default generator so that add my own generator steps. An example could be I want a step to add Sitecore.kernel refenreces

I would expected to find documentation on how to write such an extension 

The documentation contains no description on how extend the generator

**Comment by TakeitEasyAlan** [comment]
I also suggested to @Hafeok that we could have a convention (prefix with __P_ i.e. __P_[NameOfFile] and it would be added to the project as a refernce i.e __P_Packages.config.

**Comment by Hafeok** [comment]
this has been fixed and merged. Closing see #2
