### ISSUE TITLE
Correct the documentation for adding projects

### ISSUE THREAD

**Issue by jsurland** [PentiaLabs/generator-helix#59]
### User story
As a Developer, I want to have correct 'How To Add Project' documentation so that I can follow the documentation easily without confusion. (Please replace the <> areas and remove this parentheses)

![image](https://cloud.githubusercontent.com/assets/14158212/23165195/31bf88e2-f83b-11e6-8e3c-a0769c8afab6.png)

### Expected behavior
Documentation should say

yo helix:add

### Actual behavior
Documentation says

yo helix:add [Projectname]

### Steps to reproduce the behavior
RTFM :-D

**Comment by Saturate** [comment]
It works, if you define the first argument it's the default name of the project and you can skip on to the next options.

![image](https://cloud.githubusercontent.com/assets/453018/23208486/7d56db56-f8f5-11e6-82f2-09bd0b41aff8.png)

Maybe we can make it clear that it's a optional thing, or just leave it out and let powerusers use it.

**Comment by istern** [comment]
Issue being close Documentation has been updated
