### ISSUE TITLE
Adding a new project throws "Cannot find module '../../modules/powershell'"

### ISSUE THREAD

**Issue by soen** [PentiaLabs/generator-helix#62]
### User story
As a developer, I want to add a new project to my solution so that I can extend my solution.

### Expected behavior

When the command ``yo helix:add`` is invoked on the solution root folder, I expect that I'm able to add a new project to the solution.

### Actual behavior

When I run the command ``yo helix:add`` (with or without the optional ``[ProjectName]`` argument), I get the following exception:

```js
module.js:471
    throw err;
    ^

Error: Cannot find module '../../modules/powershell'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\generator-helix\generators\add\index.js:5:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

### Steps to reproduce the behavior

1. Install the latest version of the Helix generator (@1.0.10)
2. Create a new solution using the ``yo helix`` command
3. Try to add a new project to the solution using the ``yo helix:add`` command

On step 3, the error will appear.

It should be noted that this error is only present on version @1.0.10

**Comment by TakeitEasyAlan** [comment]
The Powershell & Modules are not in the package, as the packager is case sensitive???

**Comment by soen** [comment]
You're absolutely right, just checked the content of the package installed on my machine and the files/folders are indeed missing.

**Comment by saberone** [comment]
Same issue over here. Installing the previous version 1.0.9 works fine.

**Comment by TakeitEasyAlan** [comment]
Fixing coming soon :-) aarrrhhh windows, meets npm case sensitive :-(

**Comment by TakeitEasyAlan** [comment]
@saberone the latest version fixes this issue, please install the latest version :-)
