### ISSUE TITLE
Unnecessary line of code

### ISSUE THREAD

**Issue by saberone** [PentiaLabs/generator-helix#66]
### User story
As a developer, I do not want redundant code so that I can survive. 

### Expected behavior
No unnecessary line of code

### Actual behavior
This code doesn't  do something useful
```
this.settings.ProjectName = this.settings.ProjectName;
```
### Steps to reproduce the behavior
See: https://github.com/PentiaLabs/generator-helix/blob/master/generators/add/index.js#L45

**Comment by TakeitEasyAlan** [comment]
@saberone cheers -  wow that is weird, I guess we are so used to C# and the tooling :-) will fix ASAP

**Comment by Saturate** [comment]
@TakeitEasyAlan Already fixed it in #67
