### ISSUE TITLE
Generator hangs in VS package manager console and Powershell ISE

### ISSUE THREAD

**Issue by phaniav** [PentiaLabs/generator-helix#75]
@soen 
### User story
As a yo helix generator user, I want to run the generator with in VS package Manager console so that I can quickly spin a new helix solution without moving out of VS

### Expected behavior
Generator provides a way to select the solution options with in VS

### Actual behavior
VS hangs
https://sitecorechat.slack.com/files/phani_abburi/F49U0FGLT/-.powershell

### Steps to reproduce the behavior
run yo helix in VS package manager console

**Comment by Hafeok** [comment]
Hey, 

Im guessing this is VS 2015 ?

**Comment by Saturate** [comment]
It might be that VS2015 is not including the correct version of NodeJS and is using it's internal nodejs... this does not support ES6 and yeoman depends on this.

Could you check this setting:

![image](https://cloud.githubusercontent.com/assets/453018/23354499/c6aa7080-fcd1-11e6-8f70-724951c56adc.png)

If you don't have it locally try installing it from https://nodejs.org/en/ and add it to the above setting.

If this works we should update the troubleshooting guide.

**Comment by istern** [comment]
It seems to be a problem with the submodule that yeoman use inquirer https://github.com/SBoudrias/Inquirer.js/

Inqueirer is used to formulate the questions for yeoman, and if you run the example from the above link you can see it makes powershell ise and vs hangs. 
My best suggestion would be to create an issue in iquirer github pages.
