### ISSUE TITLE
Local.pubxml is missing from Project.Environment

### ISSUE THREAD

**Issue by TakeitEasyAlan** [PentiaLabs/generator-helix#79]
### User story

When adding a project I get the Local.pubxml, but it is not included in the Project.Environment when creating a solution from scratch

![image](https://cloud.githubusercontent.com/assets/9886931/23499673/56e7543a-ff2d-11e6-8c7e-e1e1423d0630.png)

### Expected behavior

 Local.pubxml is added, like when adding a project using yo helix:add

### Actual behavior

Local.pubxml is not added

### Steps to reproduce the behavior

create a new solution using yo helix, and select pentia tooling.

**Comment by Saturate** [comment]
Should we include this bugfix for the 1.2 release?

**Comment by TakeitEasyAlan** [comment]
@Saturate yes!!!
