### ISSUE TITLE
Add in Support For Module Groups

### ISSUE THREAD

**Issue by Vapok** [PentiaLabs/generator-helix#82]
### User story
As a developer, I want to be prompted for an optional Module Group name when adding a module so that I can have groupings of logical modules together.  This is documented as an optional file structure in section [2.3.1 of the Helix documentation](http://helix.sitecore.net/principles/file-structure/solutions.html).

### Expected behavior
When adding a module to Helix, during the prompts, after Vendor Name prompt, I would expect to see an optional prompt for **Module Group**.

### Actual behavior
The functionality does not prompt for Module Group.

### Steps to reproduce the behavior
Adding a module does not provide you a method for specifying a module group.

**Comment by TakeitEasyAlan** [comment]
This is fixed by TS
