### ISSUE TITLE
Add extension point for powershell scripts

### ISSUE THREAD

**Issue by saberone** [PentiaLabs/generator-helix#85]
### User story
As a developer, I want to be able to add custom powershell scripts so that I can run some custom actions like scaffolding Sitecore items or publishing unicorn stuff.

### Expected behavior
Custom script being ran from a folder that is located within the solution folder 
### Actual behavior
New functionality so... 
![Can I haz custom script](https://cdn.meme.am/cache/instances/folder881/76025881.jpg)

### Steps to reproduce the behavior
Not a bug but a new feature ;)

**Comment by Hafeok** [comment]
Hmmmm this isnt a bad idea, but i am not sure what the use case is?

Why would you want to run a powershell script when creating a new project, does it make sense to publish unicorn items when creating a new project? and scaffolding sitecore items, you can do that by adding the *.yml files to the project by using the current extension method. 

I can definitely find uses for it, but i would like to add functionality based on real world use cases and not just us coming up with cool ideas :D

**Comment by TakeitEasyAlan** [comment]
@Hafeok should we close this issues? 
and or @saberone do you have a use case for what you would use this for?

**Comment by saberone** [comment]
@TakeitEasyAlan For me the use case would be that I wouldn't need to add the Project/Feature/Foundation folders for Renderings/Templates manually in sitecore. Ideally a Powershell script would create those for me by using Powershell Extensions.

**Comment by TakeitEasyAlan** [comment]
@saberone I believe a better way to do that, would be to add the serialization folders, with the respective YAML files, and then use Unicorn to create the items in sitecore :-) Currently we do not have a way to generate a new GUID for each Yaml file, but we can solve that I hope.

**Comment by TakeitEasyAlan** [comment]
Closing this issue as it's more about how you handle item serialization and distribution - e.g. using the "old" Sitecore package manager, the "old" Sitecore serialization or "new stuff" like Hedgehog TDS or Sitecore Unicorn.
