### ISSUE TITLE
gulp setup fails

### ISSUE THREAD

**Issue by martin-bootstrap** [PentiaLabs/generator-helix#88]
### User story
As a developer, I want to understand `gulp setup` fails so that I can complete my initial project setup without errors

### Expected behavior
Setup runs without errors

### Actual behavior
<pre>
Getting Sitecore Package
Package not found locally installing from https://sitecore.myget.org/feed/sc-packages/package/nuget
Error: Find-Package : No match was found for the specified search criteria and package name 'Sitecore'. 
Try Get-PackageSource  to see all available registered package sources.
</pre>

### Steps to reproduce the behavior
* Edit solution-packages.json and replace "Sitecore.Full" with "Sitecore"...after browsing the sitecore nuget repo, I couldn't find a "Sitecore.Full" package, but there was a Sitecore one
* Replace location with https://sitecore.myget.org/feed/sc-packages/package/nuget
* Run `gulp setup`

**Comment by TakeitEasyAlan** [comment]
@martin-bootstrap sorry about the slow response it has been very busy here, I am in Prague until Monday evening, but I will look at this tuesday

**Comment by TakeitEasyAlan** [comment]
This is not an issue with with the helix generator. Please see the documentation for [sitecore-package-manager]( https://www.npmjs.com/package/@pentia/sitecore-package-manager ) by default it points to a example nuget feed which should contain the complete run time versions of the Sitecore. The documentation for sitecore-package-manager, explains how you can configure your setup to point at a nuget feed which contains the run time dependencies for sitecore (which we all hope Sitecore will do soon)
