### ISSUE TITLE
Enhancement: Remember User Preferences

### ISSUE THREAD

**Issue by patelcp** [PentiaLabs/generator-helix#89]
### User story
As a developer, I want the generator-helix to remember my preferences so that I don't have to fill them out when adding new features.

### Expected behavior
The generator should remember certain preferences such as .NET Framework version to use after first being set when the solution is generated. 

It seems this can be done using the Store property of teh question object, but have not had chance to try it.

See: Remembering User Preferences 
Link: http://yeoman.io/authoring/user-interactions.html

### Actual behavior
The Developer is promoted to provide preferences each time a new module is added. 

Such preferences include but not limited to:
* .NET Framework version
* Vendor Prefix
* Source code folder name

### Steps to reproduce the behavior
1. Create blank solution using generator-helix
   1. User is prompted to provide .NET Framework version to use
1. Add a new feature
   1. User is promoted again to provide .NET Framework version to use (I tried non-default version to validate if it remembers I selected 4.5.2 the second time).

**Comment by TakeitEasyAlan** [comment]
@chiragp supper idea we were using store initially but we had an issue with, but I will look at why it was not working :-) as I am also annoyed i have to re-enter stuff :-)

**Comment by patelcp** [comment]
I can actually do a pull request for this over the weekend. I added the store attribute and confirmed it created the .yo-rc.json file at the root level.  I have had issues running unit test before I submit pull request, seems like those are broken so can try to fix those as well.

**Comment by TakeitEasyAlan** [comment]
@chiragp thanks for the PR which fixed this issue :-)
