### ISSUE TITLE
Bug: On Helix:Add the ProjectName attribute is not validated

### ISSUE THREAD

**Issue by patelcp** [PentiaLabs/generator-helix#90]
### User story
As a generator, I want to ensure that users properly fill out the ProjectName prompt so that the generation of the add subgenerator doesn't error out.

### Expected behavior
User should not be able to leave the ProjectName prompt empty when generating a layer module.  ProjectName should be required.

### Actual behavior
User is able to hit enter and leave the ProjectName prompt empty.

### Steps to reproduce the behavior
1. Run yo helix:add
1. When prompted to fill in ProjectName leave the field empty and hit enter
1. Oontinue with remaining generation process
1. Observe error thrown because ProjectName is empty

**Comment by Saturate** [comment]
Good catch we should fix this and write a test for it.
