### ISSUE TITLE
User should not be prompted if value was passed as a option or argument 

### ISSUE THREAD

**Issue by patelcp** [PentiaLabs/generator-helix#97]
### User story
As a user, I want the generator to skip a prompt (i.e. Project Name) if I have provided the value as an argument so that I can quickly create my projects. Along with this, all prompts should have options and arguments so I can completely bypass the prompts.

### Expected behavior
When user provided a value via the option/argument (i.e. yo helix:add MyFeature), the prompt for ProjectName should be skipped.

### Actual behavior
If a prompt such as ProjectNames are provided as an argument, the generator still prompts the user to provide a ProjectName.

### Steps to reproduce the behavior
Run "yo helix:add MyFeature", and notice even though you have provided Project Name as a argument, the prompt is still displayed.

**Comment by TakeitEasyAlan** [comment]
I believe this is an issue, with Yeoman. 

In theory if you define a command line argument and the question is bound to that argument, the questions should not be answered. [Considered you should report this as an issue](http://yeoman.io/contributing/opening-issues.html) :-)

We could modify the code to do a switch on if projectName & VendowName and only ask a sub set of questions based on what was supplied, but I believe this is not how Yeoman was intended to be used. I would prefer to keep the code simple and therefore you have to enter CR and use the value passed as an argument.

Thanks you for your feedback, Alan
