### ISSUE TITLE
Using different Templates

### ISSUE THREAD

**Issue by istern** [PentiaLabs/generator-helix#99]
### User story
As a developer  I want to add different projecttypes via (Templates) the helix generator, so that i can add projects to the solution using different templates.

**Comment by TakeitEasyAlan** [comment]
@istern U should be able to code this for yourself ;-)

**Comment by TakeitEasyAlan** [comment]
see https://github.com/PentiaLabs/generator-helix#extending-the-add-generator
If it is unclear, asking for better documentation :-)
